name: diet_app
description: Diet App for helping you to achieve your fitness goals!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  stacked: ^2.3.8
  stacked_services: ^0.8.24
  get_it: ^7.2.0
  package_info: ^2.0.2
  dio: ^4.0.6
  flutter_keyboard_visibility: ^5.2.0
  adobe_xd: ^2.0.1
  carousel_slider: ^4.1.1
  flutter_svg: ^1.1.0
  another_xlider: ^1.1.0
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  flutter_rounded_date_picker: ^3.0.1
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  rive: ^0.8.4
  youtube_player_flutter: ^8.1.0
  expandable: ^5.0.1
  
  # Firebase
  firebase_core: "^1.4.0"
  firebase_auth: "^3.0.1"
  cloud_firestore: "^2.4.0"
  firebase_storage: "^10.0.1"

  # Local DB
  floor: ^1.2.0
  shared_preferences: ^2.0.15

  #alarm
  flutter_local_notifications: ^9.5.3+1
  units_converter: ^2.0.0

    # debugging
  #flutter_stetho:
  #  git: 
  #    url: git://github.com/jasonlewicki/flutter_stetho.git
  #    ref: master
  #flutter_flipperkit: ^0.0.27
  #flipperkit_sqflite_driver:
    # git:
    #   url: https://github.com/ishaquehassan/flutter_flipperkit_plugins
    #   ref: null_safety    #branch name
    #   path: packages/flipperkit_sqflite_driver

dev_dependencies:
  assets_indexer: ^0.0.10
  stacked_generator: ^0.6.5
  floor_generator: ^1.2.0
  build_runner: ^2.1.11

dependency_overrides:
  analyzer: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 800
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
